#!/bin/bash
# =============================================================================
# Dream Home Estate — server bootstrap + non-root updates (user: madhu)
#
# First-time bootstrap (once, as root):
#   export DEPLOY_USER=madhu
#   export REPO_URL=https://github.com/madhu2456/dreamhomeestate.git
#   git clone "$REPO_URL" /opt/dreamhomeestate
#   cd /opt/dreamhomeestate && chmod +x deploy.sh
#   sudo DOMAIN=dreamhomeestate.madhudadi.in ./deploy.sh
#
# Updates as madhu (GitHub Actions):
#   cd /opt/dreamhomeestate && ./deploy.sh --update
# =============================================================================

set -euo pipefail

APP_NAME="dreamhomeestate"
DEPLOY_USER="${DEPLOY_USER:-madhu}"
REPO_URL="${REPO_URL:-https://github.com/madhu2456/dreamhomeestate.git}"
BRANCH="${BRANCH:-main}"
DOMAIN="${DOMAIN:-dreamhomeestate.madhudadi.in}"
# Host port only (container uses 3000). Avoid clashes with other apps on this host.
# madhudadi.in=3000, blog=3001, deals=3002 → use 3010 for Dream Home Estate
APP_PORT="${APP_PORT:-3010}"
API_PORT="${API_PORT:-8010}"
MINIO_PORT="${MINIO_PORT:-9010}"
APP_DIR="${APP_DIR:-/opt/dreamhomeestate}"
COMPOSE="docker compose -f docker-compose.prod.yml"

MODE="bootstrap"
if [ "${1:-}" = "--update" ] || [ "${1:-}" = "update" ]; then
  MODE="update"
fi

echo "=== Dream Home Estate deployment (${MODE}) ==="
echo "    APP_DIR=${APP_DIR}"
echo "    DOMAIN=${DOMAIN}"
echo "    APP_PORT=${APP_PORT}"
echo "    API_PORT=${API_PORT}"
echo "    BRANCH=${BRANCH}"
echo "    USER=$(whoami) (target deploy user: ${DEPLOY_USER})"

# ---------------------------------------------------------------------------
need_root() {
  if [ "$(id -u)" -ne 0 ]; then
    echo "Bootstrap requires root once. Run: sudo $0"
    exit 1
  fi
}

need_docker() {
  if ! command -v docker >/dev/null 2>&1; then
    echo "Docker is not installed. Run full bootstrap as root first: sudo ./deploy.sh"
    exit 1
  fi
  if ! docker info >/dev/null 2>&1; then
    echo "Cannot talk to Docker as $(whoami)."
    echo "  usermod -aG docker ${DEPLOY_USER}  # then re-login"
    exit 1
  fi
  if ! docker compose version >/dev/null 2>&1; then
    echo "docker compose plugin missing. Install: apt-get install -y docker-compose-plugin"
    exit 1
  fi
}

install_docker() {
  if ! command -v docker &>/dev/null; then
    echo "Installing Docker..."
    curl -fsSL https://get.docker.com -o /tmp/get-docker.sh
    sh /tmp/get-docker.sh
    rm -f /tmp/get-docker.sh
    systemctl enable --now docker
  else
    echo "Docker already installed."
  fi

  if ! docker compose version &>/dev/null; then
    echo "Installing Docker Compose plugin..."
    apt-get update -y
    apt-get install -y docker-compose-plugin
  fi
}

ensure_deploy_user() {
  if ! id "${DEPLOY_USER}" >/dev/null 2>&1; then
    echo "Creating user ${DEPLOY_USER}..."
    useradd -m -s /bin/bash "${DEPLOY_USER}"
  fi
  usermod -aG docker "${DEPLOY_USER}" || true
  echo "User ${DEPLOY_USER} is in docker group."
}

ensure_env() {
  if [ ! -f "${APP_DIR}/.env" ]; then
    echo "Creating production .env with secure defaults..."
    SECRET_KEY="$(openssl rand -hex 32)"
    OAUTH_KEY="$(openssl rand -base64 32)"
    POSTGRES_PASSWORD="$(openssl rand -hex 16)"
    S3_SECRET="$(openssl rand -hex 16)"

    cat >"${APP_DIR}/.env" <<EOF
# Generated by deploy.sh for ${DOMAIN} — rotate secrets after first login
ENV=production
PROJECT_NAME=DreamHomeEstate
LIVE_DOMAIN=https://${DOMAIN}
LOG_LEVEL=info

SECRET_KEY=${SECRET_KEY}
SESSION_COOKIE_NAME=dhe_session
SESSION_MAX_AGE_SECONDS=86400
CORS_ALLOWED_ORIGINS=https://${DOMAIN}

DATABASE_URL=postgresql+asyncpg://postgres:${POSTGRES_PASSWORD}@postgres:5432/realestate
POSTGRES_USER=postgres
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=realestate
DATABASE_POOL_SIZE=10

REDIS_URL=redis://redis:6379/0

S3_ENDPOINT=http://minio:9000
S3_ACCESS_KEY=minioadmin
S3_SECRET_KEY=${S3_SECRET}
S3_REGION=us-east-1
S3_BUCKET_NAME=realestate-media
S3_PUBLIC_URL=https://${DOMAIN}/media
S3_USE_SSL=false
S3_SIGNATURE_VERSION=s3v4

OAUTH_ENCRYPTION_KEY=${OAUTH_KEY}

INSTAGRAM_APP_ID=
INSTAGRAM_APP_SECRET=
INSTAGRAM_REDIRECT_URI=https://${DOMAIN}/api/v1/social-accounts/instagram/callback

X_CLIENT_ID=
X_CLIENT_SECRET=
X_REDIRECT_URI=https://${DOMAIN}/api/v1/social-accounts/x/callback

LIVE_INSTAGRAM_PUBLISHING=true
LIVE_X_PUBLISHING=true
AI_CONTENT_ASSISTANCE=false
VIDEO_PUBLISHING=false
SCHEDULING=true
ANALYTICS_COLLECTION=false
WEBHOOKS=false
AUTO_PUBLISH_WITHOUT_REVIEW=false
WATERMARKING=false

APP_PORT=${APP_PORT}
API_PORT=${API_PORT}
MINIO_PORT=${MINIO_PORT}
NEXT_PUBLIC_API_URL=
API_INTERNAL_URL=http://api:8000
EOF
    chmod 600 "${APP_DIR}/.env"
    if id "${DEPLOY_USER}" >/dev/null 2>&1; then
      chown "${DEPLOY_USER}:${DEPLOY_USER}" "${APP_DIR}/.env" 2>/dev/null || true
    fi
    echo "  .env written at ${APP_DIR}/.env"
    echo "  Postgres password and secrets generated — create owner after first deploy."
  else
    echo ".env already exists — syncing ports / domain-related keys"
    set_env_kv APP_PORT "${APP_PORT}"
    set_env_kv API_PORT "${API_PORT}"
    set_env_kv MINIO_PORT "${MINIO_PORT}"
    set_env_kv LIVE_DOMAIN "https://${DOMAIN}"
    set_env_kv S3_PUBLIC_URL "https://${DOMAIN}/media"
    set_env_kv CORS_ALLOWED_ORIGINS "https://${DOMAIN}"
    set_env_kv INSTAGRAM_REDIRECT_URI "https://${DOMAIN}/api/v1/social-accounts/instagram/callback"
    set_env_kv X_REDIRECT_URI "https://${DOMAIN}/api/v1/social-accounts/x/callback"
  fi
}

set_env_kv() {
  local key="$1"
  local val="$2"
  local file="${APP_DIR}/.env"
  if grep -q "^${key}=" "${file}" 2>/dev/null; then
    sed -i "s|^${key}=.*|${key}=${val}|" "${file}"
  else
    echo "${key}=${val}" >>"${file}"
  fi
}

as_root() {
  if [ "$(id -u)" -eq 0 ]; then
    "$@"
  elif command -v sudo >/dev/null 2>&1 && sudo -n true 2>/dev/null; then
    sudo "$@"
  else
    return 1
  fi
}

install_nginx_from_repo() {
  local dest="/etc/nginx/sites-available/${APP_NAME}"
  local enabled="/etc/nginx/sites-enabled/${APP_NAME}"
  local http_src="${APP_DIR}/nginx/dreamhomeestate.conf"
  local ssl_src="${APP_DIR}/nginx/dreamhomeestate.ssl.conf"
  local tmp
  tmp="$(mktemp)"

  if [ ! -f "${http_src}" ]; then
    echo "  Nginx: no ${http_src} — skipping"
    return 0
  fi

  echo "Installing Nginx site → ${dest} (web :${APP_PORT}, api :${API_PORT}, minio :${MINIO_PORT})"

  if [ -f "/etc/letsencrypt/live/${DOMAIN}/fullchain.pem" ] && [ -f "${ssl_src}" ]; then
    echo "  Using SSL template (certs found for ${DOMAIN})"
    sed -e "s/__DOMAIN__/${DOMAIN}/g" \
        -e "s/__APP_PORT__/${APP_PORT}/g" \
        -e "s/__API_PORT__/${API_PORT}/g" \
        -e "s/__MINIO_PORT__/${MINIO_PORT}/g" \
        "${ssl_src}" >"${tmp}"
    if [ ! -f /etc/letsencrypt/ssl-dhparams.pem ]; then
      sed -i '/ssl_dhparam/d' "${tmp}"
    fi
    if [ ! -f /etc/letsencrypt/options-ssl-nginx.conf ]; then
      sed -i '/options-ssl-nginx.conf/d' "${tmp}"
    fi
  else
    echo "  Using HTTP template"
    sed -e "s/__DOMAIN__/${DOMAIN}/g" \
        -e "s/__APP_PORT__/${APP_PORT}/g" \
        -e "s/__API_PORT__/${API_PORT}/g" \
        -e "s/__MINIO_PORT__/${MINIO_PORT}/g" \
        "${http_src}" >"${tmp}"
  fi

  if ! as_root cp "${tmp}" "${dest}"; then
    echo "  WARNING: cannot write ${dest} (need root or passwordless sudo)."
    echo "  Install once: sudo cp ${tmp} ${dest} && sudo ln -sfn ${dest} ${enabled} && sudo nginx -t && sudo systemctl reload nginx"
    rm -f "${tmp}"
    return 0
  fi
  rm -f "${tmp}"

  as_root ln -sfn "${dest}" "${enabled}" || true
  as_root mkdir -p /var/www/html || true

  if as_root nginx -t; then
    as_root systemctl reload nginx || as_root service nginx reload || true
    echo "  Nginx reloaded for ${DOMAIN} → 127.0.0.1:${APP_PORT}"
  else
    echo "  ERROR: nginx -t failed after installing ${dest}"
    return 1
  fi
}

configure_nginx() {
  echo "Configuring Nginx reverse proxy for ${DOMAIN}..."
  apt-get update -y
  apt-get install -y nginx
  install_nginx_from_repo
  systemctl enable --now nginx
}

pull_or_clone() {
  git config --global --add safe.directory "${APP_DIR}" 2>/dev/null || true

  if [ ! -w "${APP_DIR}/.git" ] 2>/dev/null || [ ! -w "${APP_DIR}" ]; then
    echo "WARNING: ${APP_DIR} may not be fully writable by $(whoami)."
    echo "  As root: chown -R ${DEPLOY_USER}:${DEPLOY_USER} ${APP_DIR}"
  fi

  if [ -d "${APP_DIR}/.git" ]; then
    echo "Updating repository (hard reset to origin/${BRANCH})..."
    if ! git -C "${APP_DIR}" fetch origin; then
      echo "git fetch failed — check ownership of ${APP_DIR}"
      exit 1
    fi
    git -C "${APP_DIR}" checkout "${BRANCH}"
    if ! git -C "${APP_DIR}" reset --hard "origin/${BRANCH}"; then
      echo "git reset failed — fix ownership: chown -R ${DEPLOY_USER}:${DEPLOY_USER} ${APP_DIR}"
      exit 1
    fi
    git -C "${APP_DIR}" clean -fd -e .env -e 'postgres_data' -e 'minio_data' || true
  else
    mkdir -p "$(dirname "${APP_DIR}")"
    if [ -d "${APP_DIR}" ] && [ -n "$(ls -A "${APP_DIR}" 2>/dev/null | grep -v '^\.env$' || true)" ]; then
      echo "Cloning into temp then merging..."
      TMP="$(mktemp -d)"
      git clone --branch "${BRANCH}" "${REPO_URL}" "${TMP}"
      if [ -f "${APP_DIR}/.env" ]; then
        cp "${APP_DIR}/.env" "${TMP}/.env"
      fi
      rm -rf "${APP_DIR}"
      mv "${TMP}" "${APP_DIR}"
    else
      echo "Cloning ${REPO_URL}..."
      git clone --branch "${BRANCH}" "${REPO_URL}" "${APP_DIR}"
    fi
  fi
}

compose_up() {
  cd "${APP_DIR}"
  echo "Building and starting production stack..."

  ${COMPOSE} down --remove-orphans 2>/dev/null || true

  if command -v docker >/dev/null 2>&1; then
    for id in $(docker ps -q --filter "publish=${APP_PORT}" 2>/dev/null || true); do
      name="$(docker inspect -f '{{.Name}}' "${id}" 2>/dev/null || true)"
      case "${name}" in
        *dreamhome*|*realestate*)
          echo "  Stopping leftover on :${APP_PORT}: ${id}"
          docker stop "${id}" >/dev/null 2>&1 || true
          docker rm "${id}" >/dev/null 2>&1 || true
          ;;
      esac
    done
  fi

  ${COMPOSE} pull 2>/dev/null || true
  ${COMPOSE} up -d --build --remove-orphans --force-recreate

  echo "Waiting for API health..."
  for i in $(seq 1 40); do
    if ${COMPOSE} exec -T api curl -fsS http://127.0.0.1:8000/api/v1/health >/dev/null 2>&1; then
      echo "  API healthy."
      break
    fi
    if [ "$i" -eq 40 ]; then
      echo "  API health timeout — dumping logs"
      ${COMPOSE} logs --tail=80 api || true
      exit 1
    fi
    sleep 3
  done

  echo "Running database migrations..."
  ${COMPOSE} exec -T api alembic upgrade head

  echo "Container status:"
  ${COMPOSE} ps
  ${COMPOSE} logs --tail=40 || true
}

fix_ownership() {
  if [ "$(id -u)" -eq 0 ] && id "${DEPLOY_USER}" >/dev/null 2>&1; then
    chown -R "${DEPLOY_USER}:${DEPLOY_USER}" "${APP_DIR}"
    echo "Ownership of ${APP_DIR} → ${DEPLOY_USER}"
  fi
}

# ---------------------------------------------------------------------------
# Update path (non-root)
# ---------------------------------------------------------------------------
if [ "${MODE}" = "update" ]; then
  echo "    Running non-root update as $(whoami)..."
  need_docker

  # First deploy: create/clone app dir if missing
  if [ ! -d "${APP_DIR}/.git" ]; then
    echo "App not found at ${APP_DIR} — cloning ${REPO_URL}..."
    if [ ! -d "${APP_DIR}" ]; then
      if ! mkdir -p "${APP_DIR}" 2>/dev/null; then
        if command -v sudo >/dev/null 2>&1 && sudo -n true 2>/dev/null; then
          sudo mkdir -p "${APP_DIR}"
          sudo chown -R "$(whoami):$(whoami)" "${APP_DIR}"
        else
          echo "Cannot create ${APP_DIR}. As root once:"
          echo "  mkdir -p ${APP_DIR} && chown -R $(whoami):$(whoami) ${APP_DIR}"
          exit 1
        fi
      fi
    fi
  fi

  if [ ! -w "${APP_DIR}" ]; then
    echo "No write access to ${APP_DIR} as $(whoami)."
    echo "As root once: chown -R ${DEPLOY_USER}:${DEPLOY_USER} ${APP_DIR}"
    exit 1
  fi

  pull_or_clone
  ensure_env
  chmod +x "${APP_DIR}/deploy.sh" 2>/dev/null || true
  compose_up
  install_nginx_from_repo

  echo ""
  echo "=== Update complete ==="
  echo "  App:  https://${DOMAIN}  (upstream 127.0.0.1:${APP_PORT})"
  echo "  Logs: cd ${APP_DIR} && ${COMPOSE} logs -f"
  exit 0
fi

# ---------------------------------------------------------------------------
# Full bootstrap (root once)
# ---------------------------------------------------------------------------
need_root

echo "1. Updating system packages..."
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y git curl ca-certificates openssl ufw

echo "2. Installing Docker..."
install_docker

echo "3. Ensuring deploy user (${DEPLOY_USER})..."
ensure_deploy_user

echo "4. Application directory ${APP_DIR}..."
if [ ! -d "/home/${DEPLOY_USER}" ]; then
  mkdir -p "/home/${DEPLOY_USER}"
  chown "${DEPLOY_USER}:${DEPLOY_USER}" "/home/${DEPLOY_USER}"
fi
pull_or_clone
chmod +x "${APP_DIR}/deploy.sh" 2>/dev/null || true

echo "5. Environment file..."
ensure_env
fix_ownership

echo "6. Building and starting app (as ${DEPLOY_USER})..."
if [ "$(id -u)" -eq 0 ]; then
  su - "${DEPLOY_USER}" -c "cd '${APP_DIR}' && export DOMAIN='${DOMAIN}' APP_PORT='${APP_PORT}' MINIO_PORT='${MINIO_PORT}' APP_DIR='${APP_DIR}' && ./deploy.sh --update"
else
  compose_up
  install_nginx_from_repo
fi

echo "7. Nginx reverse proxy..."
configure_nginx

echo "8. Firewall..."
if command -v ufw &>/dev/null; then
  ufw allow OpenSSH || true
  ufw allow 'Nginx Full' || true
  ufw --force enable || true
fi

fix_ownership

echo ""
echo "=== Deployment complete ==="
echo "  HTTP:  http://${DOMAIN}"
echo "  App:   ${APP_DIR} (owner: ${DEPLOY_USER})"
echo "  Admin: http://${DOMAIN}/admin"
echo "  Logs:  su - ${DEPLOY_USER} -c 'cd ${APP_DIR} && docker compose -f docker-compose.prod.yml logs -f'"
echo ""
echo "  Create owner account:"
echo "    cd ${APP_DIR} && docker compose -f docker-compose.prod.yml exec api \\"
echo "      python -m app.cli create-owner admin@${DOMAIN} 'Admin' \\"
echo "      --password 'change-me' \\"
echo "      --org-name 'Dream Home Estate' \\"
echo "      --org-slug dream-home-estate"
echo ""
echo "  SSL:"
echo "    apt-get install -y certbot python3-certbot-nginx"
echo "    certbot --nginx -d ${DOMAIN}"
echo ""
echo "  GitHub Actions secrets:"
echo "    DEPLOY_HOST=<server-ip>"
echo "    DEPLOY_USER=${DEPLOY_USER}"
echo "    DEPLOY_SSH_KEY=<private key for ${DEPLOY_USER}>"
echo "    DEPLOY_PATH=${APP_DIR}   (optional)"
