"""add publication models

Revision ID: 9887137cd051
Revises: ddc5992a4316
Create Date: 2026-07-13 14:38:54.938015
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9887137cd051'
down_revision: Union[str, None] = 'ddc5992a4316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publication_outbox',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_publication_outbox_organization_id_organizations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publication_outbox'))
    )
    op.create_index('ix_pub_outbox_status_created', 'publication_outbox', ['status', 'created_at'], unique=False)
    op.create_table('publication_campaigns',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('listing_version_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('pending_approval', 'approved', 'rejected', 'scheduled', 'queued', 'publishing', 'published', 'partial_success', 'failed', 'cancelled', name='job_status_enum'), nullable=False),
    sa.Column('auto_distribute', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_publication_campaigns_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('fk_publication_campaigns_listing_id_listings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_version_id'], ['listing_versions.id'], name=op.f('fk_publication_campaigns_listing_version_id_listing_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_publication_campaigns_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publication_campaigns'))
    )
    op.create_table('publication_jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('social_account_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending_approval', 'approved', 'rejected', 'scheduled', 'queued', 'publishing', 'published', 'partial_success', 'failed', 'cancelled', name='job_status_enum', create_type=False), nullable=False),
    sa.Column('rendered_title', sa.Text(), nullable=True),
    sa.Column('rendered_body', sa.Text(), nullable=True),
    sa.Column('media_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_job_id', sa.String(length=255), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_publication_jobs_approved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campaign_id'], ['publication_campaigns.id'], name=op.f('fk_publication_jobs_campaign_id_publication_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['social_account_id'], ['social_accounts.id'], name=op.f('fk_publication_jobs_social_account_id_social_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['content_templates.id'], name=op.f('fk_publication_jobs_template_id_content_templates'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publication_jobs')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_publication_jobs_idempotency_key'))
    )
    op.create_index('ix_pub_jobs_campaign_status', 'publication_jobs', ['campaign_id', 'status'], unique=False)
    op.create_table('publication_attempts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('success', 'failed', name='attempt_status_enum'), nullable=False),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['publication_jobs.id'], name=op.f('fk_publication_attempts_job_id_publication_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publication_attempts'))
    )
    op.create_index('ix_pub_attempts_job_created', 'publication_attempts', ['job_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pub_attempts_job_created', table_name='publication_attempts')
    op.drop_table('publication_attempts')
    op.drop_index('ix_pub_jobs_campaign_status', table_name='publication_jobs')
    op.drop_table('publication_jobs')
    op.drop_table('publication_campaigns')
    op.drop_index('ix_pub_outbox_status_created', table_name='publication_outbox')
    op.drop_table('publication_outbox')
    # ### end Alembic commands ###
