"""add listings and listing_media

Revision ID: c76aa492181a
Revises: 001
Create Date: 2026-07-13 12:40:02.674778
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c76aa492181a'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('public_reference_number', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('listing_status', sa.Enum('draft', 'ready_for_review', 'approved', 'published', 'paused', 'sold', 'rented', 'expired', 'archived', name='listing_status_enum'), nullable=False),
    sa.Column('transaction_type', sa.Enum('sale', 'rent', 'lease', 'other', name='transaction_type_enum'), nullable=False),
    sa.Column('property_type', sa.Enum('apartment', 'house', 'villa', 'plot', 'commercial', 'office', 'shop', 'warehouse', 'other', name='property_type_enum'), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('negotiable', sa.Boolean(), nullable=False),
    sa.Column('deposit', sa.Integer(), nullable=True),
    sa.Column('maintenance_charges', sa.Integer(), nullable=True),
    sa.Column('area', sa.Integer(), nullable=True),
    sa.Column('area_unit', sa.String(length=20), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('balconies', sa.Integer(), nullable=True),
    sa.Column('parking_spaces', sa.Integer(), nullable=True),
    sa.Column('furnishing_status', sa.Enum('unfurnished', 'semi_furnished', 'furnished', name='furnishing_status_enum'), nullable=True),
    sa.Column('construction_status', sa.Enum('ready_to_move', 'under_construction', 'new_launch', name='construction_status_enum'), nullable=True),
    sa.Column('ownership_type', sa.Enum('freehold', 'leasehold', 'power_of_attorney', 'cooperative', name='ownership_type_enum'), nullable=True),
    sa.Column('floor_number', sa.Integer(), nullable=True),
    sa.Column('total_floors', sa.Integer(), nullable=True),
    sa.Column('address_line', sa.String(length=255), nullable=True),
    sa.Column('locality', sa.String(length=255), nullable=True),
    sa.Column('landmark', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state_region', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('key_selling_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('nearby_landmarks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('whatsapp_contact', sa.String(length=50), nullable=True),
    sa.Column('seo_title', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('og_title', sa.String(length=255), nullable=True),
    sa.Column('og_description', sa.Text(), nullable=True),
    sa.Column('og_image_url', sa.String(length=1024), nullable=True),
    sa.Column('auto_distribute', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_listings_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listings')),
    sa.UniqueConstraint('organization_id', 'public_reference_number', name='uq_listings_org_ref'),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_listings_org_slug')
    )
    op.create_index('ix_listings_org_created', 'listings', ['organization_id', 'created_at'], unique=False)
    op.create_index('ix_listings_org_status', 'listings', ['organization_id', 'listing_status'], unique=False)
    op.create_index(op.f('ix_listings_public_reference_number'), 'listings', ['public_reference_number'], unique=False)
    op.create_index('ix_listings_published_at', 'listings', ['published_at'], unique=False)
    op.create_index(op.f('ix_listings_slug'), 'listings', ['slug'], unique=False)
    op.create_table('listing_media',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('image', 'video', name='media_kind_enum'), nullable=False),
    sa.Column('original_object_key', sa.String(length=1024), nullable=False),
    sa.Column('original_file_name', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('attribution', sa.String(length=500), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_cover', sa.Boolean(), nullable=False),
    sa.Column('processing_status', sa.Enum('pending', 'processing', 'ready', 'failed', name='media_processing_status_enum'), nullable=False),
    sa.Column('variants', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('fk_listing_media_listing_id_listings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_listing_media_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listing_media'))
    )
    op.create_index('ix_listing_media_listing_id', 'listing_media', ['listing_id'], unique=False)
    op.create_index('ix_listing_media_org_id', 'listing_media', ['organization_id'], unique=False)
    op.drop_constraint('uq_organizations_slug', 'organizations', type_='unique')
    op.drop_constraint('uq_sessions_token_hash', 'sessions', type_='unique')
    op.drop_constraint('uq_users_email', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_users_email', 'users', ['email'])
    op.create_unique_constraint('uq_sessions_token_hash', 'sessions', ['token_hash'])
    op.create_unique_constraint('uq_organizations_slug', 'organizations', ['slug'])
    op.drop_index('ix_listing_media_org_id', table_name='listing_media')
    op.drop_index('ix_listing_media_listing_id', table_name='listing_media')
    op.drop_table('listing_media')
    op.drop_index(op.f('ix_listings_slug'), table_name='listings')
    op.drop_index('ix_listings_published_at', table_name='listings')
    op.drop_index(op.f('ix_listings_public_reference_number'), table_name='listings')
    op.drop_index('ix_listings_org_status', table_name='listings')
    op.drop_index('ix_listings_org_created', table_name='listings')
    op.drop_table('listings')
    # ### end Alembic commands ###
