"""add social_accounts and encrypted_oauth_credentials

Revision ID: cd5c15137ea6
Revises: c76aa492181a
Create Date: 2026-07-13 13:40:01.871966
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd5c15137ea6'
down_revision: Union[str, None] = 'c76aa492181a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_accounts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('instagram', 'x', 'mock', name='provider_enum'), nullable=False),
    sa.Column('provider_account_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('profile_image_url', sa.String(length=1024), nullable=True),
    sa.Column('account_type', sa.Enum('personal', 'business', 'creator', 'page', name='account_type_enum'), nullable=True),
    sa.Column('connection_status', sa.Enum('active', 'revoked', 'expired', 'error', name='account_connection_status_enum'), nullable=False),
    sa.Column('granted_scopes', sa.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_successful_publication_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('provider_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('capabilities_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_default_destination', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_social_accounts_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_social_accounts_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_social_accounts')),
    sa.UniqueConstraint('organization_id', 'provider', 'provider_account_id', name='uq_social_accounts_org_provider_account')
    )
    op.create_index('ix_social_accounts_org_provider_status', 'social_accounts', ['organization_id', 'provider', 'connection_status'], unique=False)
    op.create_table('encrypted_oauth_credentials',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('social_account_id', sa.UUID(), nullable=False),
    sa.Column('encrypted_access_token', sa.Text(), nullable=False),
    sa.Column('encrypted_refresh_token', sa.Text(), nullable=True),
    sa.Column('token_type', sa.String(length=50), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['social_account_id'], ['social_accounts.id'], name=op.f('fk_encrypted_oauth_credentials_social_account_id_social_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_encrypted_oauth_credentials')),
    sa.UniqueConstraint('social_account_id', name=op.f('uq_encrypted_oauth_credentials_social_account_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('encrypted_oauth_credentials')
    op.drop_index('ix_social_accounts_org_provider_status', table_name='social_accounts')
    op.drop_table('social_accounts')
    # ### end Alembic commands ###
